import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { createRequire } from 'node:module';
import ts from 'typescript';
import { fixture } from './apps-script-simulator.mjs';
const require = createRequire(import.meta.url);
function admin(f, action, payload={}) { return f.ctx.adminAction_({ action, ...payload }); }
const expected = (stock=10,tracking=true,status='active')=>({productId:'P',expectedStock:stock,expectedTracking:tracking,expectedStatus:status});
let checks=0;
function test(name,fn) { fn();checks++;console.log('PASS',name); }
test('audited stock increases/decreases, optimistic concurrency',()=>{
 const f=fixture();assert.equal(admin(f,'adminAdjustStock',{...expected(),stock:15,reason:'New stock received'}).success,true);
 let tx=f.rows('InventoryTransactions').at(-1);assert.equal(tx.type,'ADJUSTMENT_IN');assert.equal(tx.quantity,5);assert.equal(tx.stock_before,10);assert.equal(tx.stock_after,15);
 assert.equal(admin(f,'adminAdjustStock',{...expected(),stock:15,reason:'Repeated request'}).code,'INVENTORY_CHANGED');
 assert.equal(admin(f,'adminAdjustStock',{...expected(15),stock:12,reason:'Physical count correction'}).success,true);
 tx=f.rows('InventoryTransactions').at(-1);assert.equal(tx.type,'ADJUSTMENT_OUT');assert.equal(tx.quantity,-3);assert.equal(tx.stock_before,15);assert.equal(tx.stock_after,12);assert.equal(tx.note.includes('Physical count correction'),true);
});
test('stock validation and untracked protection',()=>{const f=fixture();for(const stock of [-1,1.5,'10',Infinity]) assert.equal(admin(f,'adminAdjustStock',{...expected(),stock,reason:'Stock count'}).code,'INVALID_INPUT');assert.equal(admin(f,'adminAdjustStock',{...expected(),stock:15,reason:'ab'}).code,'INVALID_INPUT');assert.equal(admin(f,'adminAdjustStock',{...expected(null,false),productId:'U',stock:15,reason:'Stock count'}).code,'UNTRACKED_PRODUCT');});
test('tracking requires initial stock and preserves audit',()=>{const f=fixture();const original=f.rows('InventoryTransactions').length;assert.equal(admin(f,'adminSetTracking',{...expected(),trackStock:false,reason:'Supplier inventory'}).success,true);assert.equal(f.rows('Products')[0].stock,10);assert.equal(f.ctx.readInventory_().products[0].stock,null);assert.equal(f.rows('InventoryTransactions').length,original);assert.equal(admin(f,'adminSetTracking',{...expected(null,false),trackStock:true,reason:'Initial count'}).code,'INVALID_INPUT');assert.equal(admin(f,'adminSetTracking',{...expected(null,false),trackStock:true,stock:7,reason:'Initial count'}).success,true);assert.equal(f.rows('InventoryTransactions').at(-1).quantity,7);});
test('inactive / active uses live storefront inventory',()=>{const f=fixture();assert.equal(admin(f,'adminSetProductStatus',{...expected(),status:'inactive'}).success,true);assert.equal(f.ctx.readInventory_().products[0].status,'inactive');assert.equal(admin(f,'adminSetProductStatus',{...expected(10,true,'inactive'),status:'active'}).success,true);assert.equal(f.ctx.readInventory_().products[0].status,'active');});
for(const tab of ['Products','InventoryTransactions'])test('stock adjustment rollback '+tab,()=>{const f=fixture();f.fail(tab);assert.equal(admin(f,'adminAdjustStock',{...expected(),stock:15,reason:'New stock received'}).code,'ADJUSTMENT_FAILED');assert.equal(f.rows('Products')[0].stock,10);assert.equal(f.rows('InventoryTransactions').length,1);assert.equal(f.props.getProperty('INVENTORY_FENCE_P'),null);});
test('interrupted inventory write fence blocks storefront and admin',()=>{const f=fixture();f.props.setProperty('INVENTORY_FENCE_P','pending');assert.equal(f.ctx.readInventory_().products[0].status,'inactive');assert.equal(admin(f,'adminAdjustStock',{...expected(),stock:15,reason:'New stock received'}).code,'ADJUSTMENT_FAILED');});
test('dashboard excludes cancellation from Dhaka today revenue and refreshes counts',()=>{const f=fixture();f.set('Orders',{created_at:'2026-09-30 23:00:00',total:1200});f.add('Orders',[{order_id:'SAD-20260930-0021',created_at:'2026-09-30 01:00:00',total:500,order_status:'Cancelled'},{order_id:'SAD-20260929-0022',created_at:'2026-09-29 23:00:00',total:999,order_status:'Delivered'}]);let d=admin(f,'adminGetDashboard').data;assert.equal(d.metrics['Today Orders'],2);assert.equal(d.metrics['Today Revenue'],1200);assert.equal(d.metrics['Pending Orders'],1);assert.equal(admin(f,'adminUpdateOrderStatus',{orderId:f.id,newStatus:'Confirmed',note:'Phone confirmation'}).success,true);assert.equal(f.rows('OrderStatusHistory').length,1);assert.equal(f.rows('Products')[0].stock,10);assert.equal(admin(f,'adminCancelOrder',{orderId:f.id,reason:'Customer request'}).success,true);d=admin(f,'adminGetDashboard').data;assert.equal(d.metrics['Today Revenue'],0);assert.equal(d.metrics['Cancelled Orders'],2);});
test('admin pagination, search, status filtering and projections',()=>{const f=fixture();for(let i=30;i<60;i++)f.add('Orders',[{order_id:`SAD-20260930-00${i}`,created_at:'2026-09-30 20:00:00',order_status:'Pending',customer_name:'Example customer',phone:'+8801700000000',total:i,full_address:'private address'}]);let result=admin(f,'adminListOrders',{page:1}).data;assert.equal(result.rows.length,25);assert.equal(result.total,31);assert.equal(Object.hasOwn(result.rows[0],'full_address'),false);assert.equal(admin(f,'adminListOrders',{page:2}).data.rows.length,6);assert.equal(admin(f,'adminListOrders',{q:'Example customer',status:'Pending',sort:'total-high'}).data.rows[0].total,59);assert.equal(admin(f,'adminListOrders',{q:'none'}).data.total,0);for(let i=0;i<31;i++)f.add('Customers',[{customer_id:`CUS-${i}`,name:'Example',phone:'+8801700000000',total_orders:1,last_address:'private'}]);result=admin(f,'adminListCustomers',{page:2}).data;assert.equal(result.rows.length,6);assert.equal(Object.hasOwn(result.rows[0],'last_address'),false);assert.equal(admin(f,'adminGetOrder',{orderId:f.id}).data.items.length,1);});
test('low-stock tabs use Phase 12 report',()=>{const f=fixture();f.set('Products',{stock:4});assert.equal(admin(f,'adminListInventory',{filter:'low'}).data.rows.length,1);f.set('Products',{stock:0});assert.equal(admin(f,'adminListInventory',{filter:'low'}).data.rows.length,0);assert.equal(admin(f,'adminListInventory',{filter:'out'}).data.rows.length,1);assert.equal(admin(f,'adminListInventory',{filter:'tracked'}).data.rows.length,1);});
test('Asia/Dhaka date boundary is used instead of UTC',()=>{
 const f=fixture();const fixed=new Date('2026-09-30T20:00:00Z');f.ctx.Date=new Proxy(Date,{construct(target,args){return args.length?new target(...args):new target(fixed);}});
 f.ctx.Utilities.formatDate=(date,zone,format)=>{assert.equal(zone,'Asia/Dhaka');const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date);const values=Object.fromEntries(parts.map(p=>[p.type,p.value]));const day=`${values.year}-${values.month}-${values.day}`;return format==='yyyy-MM-dd'?day:`${day} ${values.hour}:${values.minute}:${values.second}`;};
 f.set('Orders',{created_at:'2026-10-01 00:30:00',total:1200});f.add('Orders',[{order_id:'SAD-20260930-0030',created_at:'2026-09-30 23:59:59',total:500,order_status:'Pending'}]);const d=admin(f,'adminGetDashboard').data;assert.equal(d.today,'2026-10-01');assert.equal(d.metrics['Today Orders'],1);assert.equal(d.metrics['Today Revenue'],1200);
});
test('Apps Script admin dispatch still rejects missing secret',()=>{const f=fixture();f.props.setProperty('APPS_SCRIPT_SECRET','test-shared-secret-long');const response=f.ctx.doPost({postData:{contents:JSON.stringify({action:'adminListOrders'})}});assert.equal(JSON.parse(response.text).success,false);});
test('fenced inventory cannot be credited during cancellation',()=>{const f=fixture();f.props.setProperty('INVENTORY_FENCE_P','pending');assert.equal(f.ctx.cancelOrder(f.id,'Customer request').code,'RESTOCK_FAILED');assert.equal(f.rows('Products')[0].stock,10);assert.equal(f.rows('Orders')[0].order_status,'Pending');});
test('inactive product rejected by existing locked checkout',()=>{const f=fixture();assert.equal(admin(f,'adminSetProductStatus',{...expected(),status:'inactive'}).success,true);assert.equal(f.ctx.createOrder_({requestId:'new-inactive-request',items:[{productId:'P',quantity:1}]}).code,'PRODUCT_UNAVAILABLE');assert.equal(f.rows('Products')[0].stock,10);});
const env={NODE_ENV:'production',ADMIN_USERNAME:'test-operator',ADMIN_PASSWORD:'test-only-password-long',ADMIN_SESSION_SECRET:'test-only-signing-secret-with-enough-length'};
let cookie;
const exports={};
const sessionJS=ts.transpileModule(fs.readFileSync('lib/adminSession.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(sessionJS,{exports,Buffer,URL,process:{env},Date,require:name=>name==='server-only'?{}:name==='next/headers'?{cookies:async()=>({get:()=>({value:cookie})})}:name==='next/navigation'?{redirect:()=>{throw Error('REDIRECT');}}:require(name)});
test('wrong user/password, valid session, invalid/tampered/expired sessions',()=>{assert.equal(exports.checkCredentials('wrong',env.ADMIN_PASSWORD),false);assert.equal(exports.checkCredentials(env.ADMIN_USERNAME,'wrong'),false);assert.equal(exports.checkCredentials(env.ADMIN_USERNAME,env.ADMIN_PASSWORD),true);const token=exports.issueSession(1000);assert.equal(exports.verifySession(token,1001),true);assert.equal(exports.verifySession(token+'x',1001),false);assert.equal(exports.verifySession(token,1000+8*60*60*1000),false);assert.equal(exports.verifySession('invalid'),false);assert.equal(exports.verifySession(token,999),false);env.ADMIN_PASSWORD+='changed';assert.equal(exports.verifySession(token,1001),false);env.ADMIN_PASSWORD=env.ADMIN_PASSWORD.slice(0,-7);assert.equal(exports.cookieOptions.httpOnly,true);assert.equal(exports.cookieOptions.secure,true);assert.equal(exports.cookieOptions.sameSite,'strict');});
test('credential config fails closed and login attempts limited',()=>{const saved=env.ADMIN_SESSION_SECRET;env.ADMIN_SESSION_SECRET='';assert.equal(exports.adminConfigured(),false);env.ADMIN_SESSION_SECRET=saved;for(let i=0;i<10;i++)assert.equal(exports.consumeLoginAttempt(1000),true);assert.equal(exports.consumeLoginAttempt(1001),false);assert.equal(exports.consumeLoginAttempt(1000+15*60*1000),true);});
test('cross-origin/missing-origin rejected',()=>{assert.equal(exports.sameOrigin(new Request('https://sadira.test/api/admin/mutate',{headers:{origin:'https://sadira.test'}})),true);assert.equal(exports.sameOrigin(new Request('https://sadira.test/api/admin/mutate',{headers:{origin:'https://evil.test'}})),false);assert.equal(exports.sameOrigin(new Request('https://sadira.test/api/admin/mutate')),false);});
await assert.rejects(exports.requireAdmin(),/REDIRECT/);
console.log(`${checks} Phase 13 checks passed; unauthenticated protected-route redirect verified.`);
