import Link from "next/link";
import { ChevronDown } from "lucide-react";
import { InfoPage } from "@/components/public/InfoPage";
import { ROUTES } from "@/lib/constants";
import { publicMetadata } from "@/lib/publicMetadata";
export const metadata = publicMetadata("FAQ", "Answers to common questions about ordering, payment, delivery and contacting Sadira.", ROUTES.faq);
const faqs = [{ question: "How do I place an order?", answer: "Choose your product options, use Add to Cart or Buy Now, complete checkout, and submit the order. Once successfully saved, an Order ID is shown. If online checkout is unavailable, contact Sadira for assistance." }, { question: "How can I confirm my order?", answer: "After a successful order, the site may provide a WhatsApp confirmation option. This opens a prepared message for you to review and send. The website creates the order before this step; opening WhatsApp does not create an order." }, { question: "What payment method is available?", answer: "Current online checkout supports Cash on Delivery." }, { question: "Do you deliver across Bangladesh?", answer: "Yes, delivery is available across Bangladesh. Delivery charges are shown during available online checkout. For delivery timing or a question about your address, please contact Sadira." }, { question: "Can I order through Facebook or Instagram?", answer: "Customers can contact Sadira through the official Facebook, Instagram or WhatsApp channels for assistance. Conversations on those platforms are separate from the website’s order system." }, { question: "How do I choose a size?", answer: "Available sizes vary by product. Check the options on the product page. For detailed measurements, contact Sadira before placing your order." }, { question: "Can I return or exchange an item?", answer: "Exchange availability and conditions may depend on the product and order situation. Please contact Sadira before returning any item." }];
export default function FaqPage() {
  return <InfoPage title="FAQ" intro="A little guidance, from choosing a style to placing your order."><h2>Ordering & customer care</h2><div className="mt-6 divide-y divide-line border-y border-line">{faqs.map(faq => <details key={faq.question} className="group py-2"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between gap-5 py-3 text-base font-medium [&::-webkit-details-marker]:hidden"><span>{faq.question}</span><ChevronDown aria-hidden="true" className="size-4 shrink-0 text-muted transition-transform group-open:rotate-180" /></summary><p className="pb-4 text-sm leading-relaxed text-muted">{faq.answer}</p></details>)}</div><p>Need more help? Visit our <Link href={ROUTES.contact}>contact page</Link>, <Link href={ROUTES.sizeGuide}>size guide</Link> or <Link href={ROUTES.returnExchange}>Return & Exchange page</Link>.</p></InfoPage>;
}
