import Image from "next/image";
import Link from "next/link";
import abayaPhoto from "@/public/catalog/abaya/sad-abaya-001/1.jpeg";
import { InfoPage } from "@/components/public/InfoPage";
import { ButtonLink } from "@/components/ui/Button";
import { ROUTES } from "@/lib/constants";
import { publicMetadata } from "@/lib/publicMetadata";
export const metadata = publicMetadata("About Sadira", "Get to know Sadira: modest styles, everyday comfort and customer care.", ROUTES.about);
const values = [{ title: "Modesty", text: "Styles that complement a modest wardrobe." }, { title: "Comfort", text: "Everyday ease is central to how we think about our collection." }, { title: "Elegance", text: "A thoughtful balance of simplicity and personal expression." }, { title: "Quality", text: "Attention to product details and clear information about each style." }, { title: "Customer Care", text: "Helping you choose through our official contact channels." }];
const collection = [["Abaya", "abaya"], ["Burka", "burka"], ["Niqab", "niqab"], ["Scarf", "scarf"], ["Combo", "combo"]] as const;
export default function AboutPage() {
  return <InfoPage title="About Sadira" intro="Modest fashion, thoughtfully selected for the everyday." wide><div className="grid items-center gap-10 md:grid-cols-2 lg:gap-16"><section className="public-reading"><p className="public-eyebrow">A wardrobe that feels like you</p><h2 className="mt-4">Our Story</h2><p>Sadira is a modest fashion brand focused on elegant, comfortable and thoughtfully selected styles for everyday wear.</p><p>Our collection brings together modest clothing and accessories, with an emphasis on finding pieces that fit your style and your day.</p><ButtonLink href={ROUTES.shop} className="mt-5">Explore the collection</ButtonLink></section><figure className="mx-auto w-full max-w-sm"><Image src={abayaPhoto} alt="Beige Abaya Elara with a gathered yoke and ruffled cuffs from the Sadira catalog" sizes="(min-width: 768px) 384px, 90vw" className="h-auto w-full rounded-[2rem]" /><figcaption className="mt-3 text-center text-xs text-muted">Abaya Elara · From our collection</figcaption></figure></div><section aria-labelledby="values-heading" className="mt-16 border-t border-line pt-12 md:mt-20"><p className="public-eyebrow">What matters to us</p><h2 id="values-heading" className="mt-4 text-3xl">Our Values</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{values.map((value, i) => <div key={value.title} className="rounded-2xl border border-line bg-white p-5"><p aria-hidden="true" className="text-xs text-muted">0{i + 1}</p><h3 className="mt-5 text-xl">{value.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted">{value.text}</p></div>)}</div></section><section className="mt-12 rounded-2xl border border-line bg-blush/30 p-6 md:p-10"><h2 className="text-3xl">Our Collection</h2><p className="mt-4 max-w-xl text-sm leading-relaxed text-muted">Explore Abaya, Burka, Niqab, Scarf, Combo and Accessories. Available styles and options are shown on each product page.</p><nav aria-label="Explore the collection" className="mt-6 flex flex-wrap gap-3">{collection.map(([label, slug]) => <Link key={slug} href={ROUTES.shopCategory(slug)} className="inline-flex min-h-11 items-center rounded-full border border-line bg-white px-5 text-sm hover:border-foreground">{label}</Link>)}<Link href={ROUTES.shopGroup("accessories")} className="inline-flex min-h-11 items-center rounded-full border border-line bg-white px-5 text-sm hover:border-foreground">Accessories</Link></nav></section></InfoPage>;
}
