import Link from "next/link";
import { listInventory, safeLoad } from "@/services/adminService";
import { Badge, DataTable, Heading, LoadError, Pagination } from "@/components/admin/Data";
import { ProductActions } from "@/components/admin/ProductActions";
export default async function Products({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams; const query = Object.fromEntries(Object.entries(raw).filter((p): p is [string, string] => typeof p[1] === "string"));
  const data = await safeLoad(() => listInventory(query));
  return <><Heading title="Products" description="Add products, edit photos and prices, and manage stock." /><div className="admin-inline-actions" style={{ marginBottom: 20 }}><Link className="admin-button primary" href="/admin/products/new">+ Add product</Link></div><section className="admin-card"><form className="admin-filters" action="/admin/products"><label>Search products<input name="q" defaultValue={query.q} placeholder="Product name or ID" maxLength={100} /></label><button className="admin-button primary">Search</button></form>{!data ? <LoadError /> : <><DataTable rows={data.rows} columns={[{ key: "product_name", label: "Product" }, { key: "product_id", label: "Product ID" }, { key: "category", label: "Category" }, { key: "track_stock", label: "Track Stock", render: r => r.track_stock ? "On" : "Off" }, { key: "stock", label: "Stock", render: r => r.track_stock ? String(r.stock === "" ? "Invalid" : r.stock) : "Untracked" }, { key: "status", label: "Status", render: r => <Badge value={r.status} /> }, { key: "updated_at", label: "Updated" }, { key: "actions", label: "Actions", render: r => <><Link className="admin-button" href={`/admin/products/${encodeURIComponent(String(r.product_id))}`}>Edit product</Link><ProductActions product={r} /></> }]} empty="No products found." /><Pagination data={data} base="/admin/products" query={query} /></>}</section></>;
}
