/**
 * Sadira — order + inventory endpoint (Google Apps Script Web App → Google Sheets).
 *
 * Only the Sadira Next.js SERVER calls this (POST /api/orders, GET /api/inventory
 * → here). The browser never does, and the shared secret never leaves the server.
 *
 * Sources of truth:
 *   - Product content, prices, variants → the Catalog tab (Catalog.gs).
 *     Next.js re-validates them; this script checks again under the order lock.
 *   - Live stock + availability of tracked products → the Products tab HERE.
 *     This script is the only place tracked stock is checked for an order and
 *     deducted, always under the same script lock as the order write.
 *
 * Order flow (doPost): check the payload shape and arithmetic → re-check the
 * request_id (idempotency) → under a script lock: re-check the request_id →
 * check live stock/status per product (quantities summed across variants) →
 * generate the Order ID (SAD-YYYYMMDD-0001, daily sequence, Asia/Dhaka) → write
 * Orders + OrderItems → deduct tracked stock + log InventoryTransactions →
 * create/update the Customer. Any failure undoes everything written for that
 * order (rows removed, stock and customer restored).
 *
 * Other action (same secret): { action: "inventory" } → live Products stock.
 *
 * Script Properties (Project Settings → Script properties):
 *   APPS_SCRIPT_SECRET  required — same value as the Next.js server env var
 *   SPREADSHEET_ID      optional — omit when this script is bound to the Sheet
 *
 * InventorySeed.gs (generated by `npm run catalog:prepare`) must be in the same
 * Apps Script project; setupInventory() uses it. See README.md in this folder.
 */

var TIMEZONE = 'Asia/Dhaka';
var LOCK_TIMEOUT_MS = 30000;
var MAX_ITEMS = 50;

/** Tab → required headers. Existing tabs keep their data; missing headers are appended. */
var SHEET_HEADERS = {
  Orders: [
    'request_id', 'order_id', 'created_at', 'customer_id', 'customer_name', 'phone',
    'alternative_phone', 'email', 'division', 'district', 'area', 'full_address',
    'postal_code', 'delivery_area', 'subtotal', 'delivery_charge', 'discount', 'total',
    'payment_method', 'payment_status', 'order_status', 'customer_note', 'whatsapp_confirmation',
    'status_updated_at', 'status_note', 'cancelled_at', 'cancel_reason', 'restock_status'
  ],
  OrderItems: [
    'order_item_id', 'order_id', 'product_id', 'product_name', 'product_slug', 'category',
    'size', 'color', 'design', 'quantity', 'unit_price', 'line_total'
  ],
  Customers: [
    'customer_id', 'name', 'phone', 'alternative_phone', 'email', 'last_address', 'division',
    'district', 'area', 'postal_code', 'first_order_at', 'last_order_at', 'total_orders'
  ],
  // Live inventory is separate from product content, preserving stock on edits.
  Products: ['product_id', 'product_name', 'track_stock', 'stock', 'status', 'updated_at'],
  Catalog: ['product_id', 'slug', 'product_json', 'revision', 'updated_at'],
  CatalogImages: ['upload_key', 'file_id', 'mime', 'created_at'],
  InventoryTransactions: [
    'transaction_id', 'created_at', 'product_id', 'order_id', 'type', 'quantity',
    'stock_before', 'stock_after', 'note'
  ],
  OrderStatusHistory: ['history_id', 'created_at', 'order_id', 'from_status', 'to_status', 'note', 'source'],
  // Reserved for a later phase.
  Coupons: []
};

var DIVISIONS = ['Dhaka', 'Chattogram', 'Rajshahi', 'Khulna', 'Barishal', 'Sylhet', 'Rangpur', 'Mymensingh'];
var DELIVERY_AREAS = { 'inside-dhaka': 'Inside Dhaka', 'outside-dhaka': 'Outside Dhaka' };

// ---- Web app entry points ----------------------------------------------------

function doPost(e) {
  try {
    var body = parseBody_(e);
    if (!body) return json_({ success: false, error: 'Invalid request.' });
    if (!isAuthorized_(body.secret)) return json_({ success: false, error: 'Unauthorized.' });

    if (body.action === 'catalog') return json_(readCatalog_());
    if (body.action === 'catalogImage') return json_(readCatalogImage_(body));
    if (body.action === 'adminSaveProduct') return json_(saveCatalogProduct_(body));
    if (body.action === 'adminUploadProductImage') return json_(uploadCatalogImage_(body));

    if (typeof body.action === 'string' && body.action.indexOf('admin') === 0) return json_(adminAction_(body));
    if (body.action === 'updateOrderStatus') return json_(updateOrderStatus(body.orderId, body.newStatus, body.note));
    if (body.action === 'cancelOrder') return json_(cancelOrder(body.orderId, body.reason));
    if (body.action === 'getLowStockProducts') return json_(getLowStockProducts());
    if (body.action === 'inventory') return json_(readInventory_());
    if (body.action !== undefined && body.action !== 'order') return json_({ success: false, error: 'Invalid request.' });

    var problem = validatePayload_(body);
    if (problem) {
      console.warn('Rejected order payload: ' + problem);
      return json_({ success: false, error: 'Invalid order data.' });
    }

    return json_(createOrder_(body));
  } catch (err) {
    // Details go to the Apps Script execution log only — never to the website.
    console.error('Request failed: ' + (err && err.stack ? err.stack : err));
    return json_({ success: false, error: 'Unable to create order.' });
  }
}

/** Health check for the deployment URL (no data exposed). */
function doGet() {
  return json_({ ok: true, service: 'sadira-orders' });
}

/** Run once from the editor: creates tabs/headers and sets the sheet timezone. Never deletes data. */
function setup() {
  var ss = getSpreadsheet_();
  ss.setSpreadsheetTimeZone(TIMEZONE);
  ensureSheets_(ss);
}

/**
 * Run from the editor after setup() — and again after products are added to the
 * catalog and InventorySeed.gs is regenerated. Adds a Products row for every
 * catalog product that doesn't have one yet:
 *   known catalog stock → track_stock TRUE,  stock = that number (initial seed only)
 *   unknown (null)      → track_stock FALSE, stock blank (never 0 — 0 means sold out)
 * Existing rows are NEVER changed, so live stock is never reset.
 */
function setupInventory() {
  var seed = typeof SADIRA_PRODUCT_SEED === 'undefined' ? null : SADIRA_PRODUCT_SEED;
  if (!seed || !seed.length) throw new Error('InventorySeed.gs is missing from this Apps Script project.');

  var lock = LockService.getScriptLock();
  if (!lock.tryLock(LOCK_TIMEOUT_MS)) throw new Error('Could not obtain the lock — try again.');
  try {
    var ss = getSpreadsheet_();
    var t = ensureSheets_(ss);
    var existing = {};
    columnValues_(t.Products, 'product_id').forEach(function (id) { existing[String(id).trim()] = true; });
    var now = Utilities.formatDate(new Date(), TIMEZONE, 'yyyy-MM-dd HH:mm:ss');
    var rows = seed.filter(function (p) { return !existing[p.productId]; }).map(function (p) {
      var tracked = isWhole_(p.stock, 0);
      return {
        product_id: p.productId,
        product_name: p.productName,
        track_stock: tracked,
        stock: tracked ? p.stock : '',
        status: 'active',
        updated_at: now
      };
    });
    if (rows.length > 0) appendRows_(t.Products, rows);
    SpreadsheetApp.flush();
    console.log('setupInventory: added ' + rows.length + ' product(s); ' +
      (seed.length - rows.length) + ' already existed and were left unchanged.');
    return rows.length;
  } finally {
    lock.releaseLock();
  }
}

// ---- Request handling --------------------------------------------------------

function parseBody_(e) {
  if (!e || !e.postData || typeof e.postData.contents !== 'string') return null;
  if (e.postData.contents.length > 1500000) return null;
  try {
    var body = JSON.parse(e.postData.contents);
    if (e.postData.contents.length > 100000 && body.action !== 'adminUploadProductImage') return null;
    return body && typeof body === 'object' ? body : null;
  } catch (err) {
    return null;
  }
}

function isAuthorized_(provided) {
  var expected = PropertiesService.getScriptProperties().getProperty('APPS_SCRIPT_SECRET');
  if (!expected || expected.length < 16 || typeof provided !== 'string') return false;
  if (provided.length !== expected.length) return false;
  var diff = 0; // compare every character (no early exit)
  for (var i = 0; i < expected.length; i++) diff |= expected.charCodeAt(i) ^ provided.charCodeAt(i);
  return diff === 0;
}

function isText_(value, max, optional) {
  if (optional && (value === null || value === undefined || value === '')) return true;
  return typeof value === 'string' && value.trim().length > 0 && value.length <= max;
}

function isWhole_(value, min) {
  return typeof value === 'number' && Math.floor(value) === value && value >= min;
}

/** Returns a reason string when the payload is unacceptable, or null. */
function validatePayload_(b) {
  if (!isText_(b.requestId, 64) || !/^[A-Za-z0-9-]{8,64}$/.test(b.requestId)) return 'requestId';

  var c = b.customer;
  if (!c || typeof c !== 'object') return 'customer';
  if (!isText_(c.name, 80)) return 'customer.name';
  if (!/^\+8801[3-9]\d{8}$/.test(c.phone || '')) return 'customer.phone';
  if (c.alternativePhone && !/^\+8801[3-9]\d{8}$/.test(c.alternativePhone)) return 'customer.alternativePhone';
  if (!isText_(c.email, 120, true)) return 'customer.email';

  var d = b.delivery;
  if (!d || typeof d !== 'object') return 'delivery';
  if (DIVISIONS.indexOf(d.division) === -1) return 'delivery.division';
  if (!isText_(d.district, 60) || !isText_(d.area, 80) || !isText_(d.address, 300)) return 'delivery.address';
  if (d.postalCode && !/^\d{4}$/.test(d.postalCode)) return 'delivery.postalCode';
  if (!DELIVERY_AREAS[d.deliveryArea]) return 'delivery.deliveryArea';

  if (!Array.isArray(b.items) || b.items.length === 0 || b.items.length > MAX_ITEMS) return 'items';
  var subtotal = 0;
  for (var i = 0; i < b.items.length; i++) {
    var it = b.items[i];
    if (!it || !isText_(it.productId, 64) || !isText_(it.productName, 200)) return 'items[' + i + ']';
    if (!isText_(it.productSlug, 200) || !isText_(it.category, 60)) return 'items[' + i + ']';
    if (!isText_(it.size, 60, true) || !isText_(it.color, 60, true) || !isText_(it.design, 60, true)) {
      return 'items[' + i + '].options';
    }
    if (!isWhole_(it.quantity, 1) || !isWhole_(it.unitPrice, 0)) return 'items[' + i + '].amounts';
    if (it.lineTotal !== it.unitPrice * it.quantity) return 'items[' + i + '].lineTotal';
    subtotal += it.lineTotal;
  }

  if (b.subtotal !== subtotal) return 'subtotal';
  if (!isWhole_(b.deliveryCharge, 0) || !isWhole_(b.discount, 0)) return 'charges';
  if (b.total !== b.subtotal - b.discount + b.deliveryCharge) return 'total';
  if (b.paymentMethod !== 'cod') return 'paymentMethod';
  if (!isText_(b.note, 500, true)) return 'note';
  return null;
}

// ---- Order creation (under lock) ---------------------------------------------

function createOrder_(b) {
  var ss = getSpreadsheet_();

  // Idempotency, fast path: a retry of an already-saved request doesn't wait for the lock.
  var saved = findExistingOrder_(ss, b.requestId);
  if (saved) return saved;

  var lock = LockService.getScriptLock();
  if (!lock.tryLock(LOCK_TIMEOUT_MS)) throw new Error('Could not obtain the order lock.');

  try {
    var t = ensureSheets_(ss);

    // Idempotency, authoritative: re-check inside the lock (the same request may have just finished).
    var existing = findRow_(t.Orders, 'request_id', b.requestId);
    if (existing) return duplicateResponse_(existing);

    // Recheck content under the same lock as catalog edits and order writes.
    if (typeof checkCatalogOrder_ === 'function') {
      var catalogProblem = checkCatalogOrder_(t, b.items);
      if (catalogProblem) return catalogProblem;
    }

    // Live stock check BEFORE anything is written. Quantities are summed per product,
    // so Design 1 × 2 + Design 2 × 3 is checked — and later deducted — as 5.
    var inventory = loadInventory_(t.Products);
    var requested = {};
    var productIds = [];
    b.items.forEach(function (it) {
      if (!requested[it.productId]) {
        requested[it.productId] = 0;
        productIds.push(it.productId);
      }
      requested[it.productId] += it.quantity;
    });

    var deductions = []; // { product, quantity } for tracked products only
    for (var p = 0; p < productIds.length; p++) {
      var productId = productIds[p];
      var product = inventory[productId];
      if (!product) {
        // No Products row yet: stock unknown → untracked (run setupInventory() after adding products).
        console.warn('No Products row for ' + productId + ' — treated as untracked stock.');
        continue;
      }
      if (!product.active) return { success: false, code: 'PRODUCT_UNAVAILABLE', productId: productId };
      if (!product.trackStock) continue; // untracked: no stock check, no transaction
      if (product.stock === null) {
        console.error('Products row for ' + productId + ' has track_stock TRUE but no valid stock.');
        return { success: false, code: 'PRODUCT_UNAVAILABLE', productId: productId };
      }
      if (requested[productId] > product.stock) {
        return { success: false, code: 'INSUFFICIENT_STOCK', productId: productId, available: product.stock };
      }
      deductions.push({ product: product, quantity: requested[productId] });
    }

    var now = new Date();
    var createdAt = Utilities.formatDate(now, TIMEZONE, 'yyyy-MM-dd HH:mm:ss');
    var orderId = nextOrderId_(t.Orders, now);
    var customer = findRow_(t.Customers, 'phone', b.customer.phone);
    var customerId = customer ? String(customer.values.customer_id) : nextCustomerId_(t.Customers);

    var c = b.customer;
    var d = b.delivery;
    var undo = []; // reverses each completed write; run newest-first if anything fails

    try {
      undo.push(deleteRowsUndo_(appendRows_(t.Orders, [{
        request_id: b.requestId,
        order_id: orderId,
        created_at: createdAt,
        customer_id: customerId,
        customer_name: c.name,
        phone: c.phone,
        alternative_phone: c.alternativePhone || '',
        email: c.email || '',
        division: d.division,
        district: d.district,
        area: d.area,
        full_address: d.address,
        postal_code: d.postalCode || '',
        delivery_area: DELIVERY_AREAS[d.deliveryArea],
        subtotal: b.subtotal,
        delivery_charge: b.deliveryCharge,
        discount: b.discount,
        total: b.total,
        // Operational fields are set here, never by the browser or the website.
        payment_method: 'COD',
        payment_status: 'Pending',
        order_status: 'Pending',
        restock_status: 'Not Required',
        status_updated_at: createdAt,
        customer_note: b.note || '',
        whatsapp_confirmation: 'Pending'
      }])));

      undo.push(deleteRowsUndo_(appendRows_(t.OrderItems, b.items.map(function (it, i) {
        return {
          order_item_id: orderId + '-' + pad_(i + 1, 2),
          order_id: orderId,
          product_id: it.productId,
          product_name: it.productName,
          product_slug: it.productSlug,
          category: it.category,
          size: it.size || '',
          color: it.color || '',
          design: it.design || '',
          quantity: it.quantity,
          unit_price: it.unitPrice,
          line_total: it.lineTotal
        };
      }))));

      // Deduct tracked stock — one SALE per product. The row is snapshotted first so a
      // later failure restores the previous stock.
      var transactions = [];
      deductions.forEach(function (x) {
        var before = x.product.stock;
        var after = before - x.quantity;
        if (after < 0) throw new Error('Refusing negative stock for ' + x.product.productId); // checked above
        undo.push(updateRowUndo_(t.Products, x.product.row));
        updateRow_(t.Products, x.product.row, { stock: after, updated_at: createdAt });
        transactions.push({
          created_at: createdAt,
          product_id: x.product.productId,
          order_id: orderId,
          type: 'SALE',
          quantity: -x.quantity,
          stock_before: before,
          stock_after: after,
          note: 'Order placed'
        });
      });
      if (transactions.length > 0) {
        var firstTx = nextSequence_(t.InventoryTransactions, 'transaction_id', 'INV-');
        transactions.forEach(function (tx, i) { tx.transaction_id = 'INV-' + pad_(firstTx + i, 6); });
        undo.push(deleteRowsUndo_(appendRows_(t.InventoryTransactions, transactions)));
      }

      var customerFields = {
        name: c.name,
        phone: c.phone,
        last_address: [d.address, d.area, d.district, d.division].join(', '),
        division: d.division,
        district: d.district,
        area: d.area,
        last_order_at: createdAt
      };
      // Keep previously known optional details unless new ones were given.
      if (c.alternativePhone) customerFields.alternative_phone = c.alternativePhone;
      if (c.email) customerFields.email = c.email;
      if (d.postalCode) customerFields.postal_code = d.postalCode;

      if (customer) {
        customerFields.total_orders = (Number(customer.values.total_orders) || 0) + 1;
        undo.push(updateRowUndo_(t.Customers, customer.row));
        updateRow_(t.Customers, customer.row, customerFields);
      } else {
        customerFields.customer_id = customerId;
        customerFields.first_order_at = createdAt;
        customerFields.total_orders = 1;
        undo.push(deleteRowsUndo_(appendRows_(t.Customers, [customerFields])));
      }

      SpreadsheetApp.flush();
    } catch (err) {
      rollback_(undo);
      throw err;
    }

    return { success: true, orderId: orderId, createdAt: createdAt };
  } finally {
    lock.releaseLock();
  }
}

/** The saved order for this request_id as a success response, or null. Read-only (safe outside the lock). */
function findExistingOrder_(ss, requestId) {
  var sheet = ss.getSheetByName('Orders');
  if (!sheet || sheet.getLastColumn() === 0) return null;
  var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0].map(String);
  var row = findRow_({ sheet: sheet, headers: headers }, 'request_id', requestId);
  return row ? duplicateResponse_(row) : null;
}

function duplicateResponse_(row) {
  return {
    success: true,
    orderId: String(row.values.order_id),
    createdAt: formatTimestamp_(row.values.created_at),
    duplicate: true
  };
}

/** Undo for appended rows: delete them. */
function deleteRowsUndo_(appended) {
  return function () { appended.table.sheet.deleteRows(appended.row, appended.count); };
}

/** Undo for an in-place update: snapshot the row now, write it back on rollback. */
function updateRowUndo_(table, row) {
  var range = table.sheet.getRange(row, 1, 1, table.headers.length);
  var snapshot = range.getValues()[0];
  return function () { range.setValues([snapshot.map(cell_)]); };
}

/** Reverses a failed order's writes, newest first. Each step runs even if an earlier one fails. */
function rollback_(undo) {
  for (var i = undo.length - 1; i >= 0; i--) {
    try {
      undo[i]();
    } catch (err) {
      console.error('Rollback step failed: ' + err);
    }
  }
  SpreadsheetApp.flush();
}

/** SAD-YYYYMMDD-NNNN, the day's highest sequence + 1 (Bangladesh date). Call under lock. */
function nextOrderId_(table, now) {
  var prefix = 'SAD-' + Utilities.formatDate(now, TIMEZONE, 'yyyyMMdd') + '-';
  var max = 0;
  columnValues_(table, 'order_id').forEach(function (value) {
    var id = String(value);
    if (id.indexOf(prefix) === 0) {
      var n = parseInt(id.substring(prefix.length), 10);
      if (n > max) max = n;
    }
  });
  return prefix + pad_(max + 1, 4);
}

/** CUS-000001, CUS-000002, … (highest existing + 1). Call under lock. */
function nextCustomerId_(table) {
  return 'CUS-' + pad_(nextSequence_(table, 'customer_id', 'CUS-'), 6);
}

/** Highest numeric suffix of `prefix`NNNN in a column, + 1 (never a row number). Call under lock. */
function nextSequence_(table, header, prefix) {
  var pattern = new RegExp('^' + prefix + '(\\d+)$');
  var max = 0;
  columnValues_(table, header).forEach(function (value) {
    var match = pattern.exec(String(value));
    if (match && parseInt(match[1], 10) > max) max = parseInt(match[1], 10);
  });
  return max + 1;
}

// ---- Inventory ---------------------------------------------------------------

/**
 * Products tab → { productId: { productId, row, trackStock, stock, active, status, updatedAt } }.
 *   track_stock: checkbox or TRUE/FALSE text.
 *   stock:       for tracked products a whole number ≥ 0; anything else → null
 *                (misconfigured → not sellable). Ignored for untracked products.
 *   status:      blank or "active" = sellable; anything else (e.g. "inactive") = not.
 */
function loadInventory_(table) {
  var inventory = {};
  var lastRow = table.sheet.getLastRow();
  if (lastRow < 2) return inventory;
  var col = {};
  table.headers.forEach(function (h, i) { col[h] = i; });
  var values = table.sheet.getRange(2, 1, lastRow - 1, table.headers.length).getValues();
  values.forEach(function (r, i) {
    var productId = String(r[col.product_id]).trim();
    if (!productId || inventory[productId]) return; // first row wins if a product is listed twice
    var trackRaw = r[col.track_stock];
    var trackStock = trackRaw === true || /^(true|yes|1)$/i.test(String(trackRaw).trim());
    var stockRaw = r[col.stock];
    var stockNum = typeof stockRaw === 'number' ? stockRaw : String(stockRaw).trim() === '' ? NaN : Number(stockRaw);
    var statusText = String(r[col.status]).trim().toLowerCase();
    var fenced = PropertiesService.getScriptProperties().getProperty('INVENTORY_FENCE_' + productId);
    var active = !fenced && (statusText === '' || statusText === 'active');
    inventory[productId] = {
      productId: productId,
      row: i + 2,
      trackStock: trackStock,
      stock: trackStock && isWhole_(stockNum, 0) ? stockNum : null,
      active: active,
      status: active ? 'active' : 'inactive',
      updatedAt: formatTimestamp_(r[col.updated_at])
    };
  });
  return inventory;
}

/** { action: "inventory" } → live stock for the storefront. Read-only; no row numbers or sheet details. */
function readInventory_() {
  var sheet = getSpreadsheet_().getSheetByName('Products');
  if (!sheet || sheet.getLastColumn() === 0) return { success: true, products: [] };
  var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0].map(String);
  var inventory = loadInventory_({ sheet: sheet, headers: headers });
  return {
    success: true,
    products: Object.keys(inventory).map(function (id) {
      var p = inventory[id];
      return {
        productId: p.productId,
        trackStock: p.trackStock,
        // Untracked → null (unknown, NOT zero). A tracked row with invalid stock can't be sold → 0.
        stock: p.trackStock ? (p.stock === null ? 0 : p.stock) : null,
        status: p.status,
        updatedAt: p.updatedAt
      };
    })
  };
}

// ---- Sheet helpers -----------------------------------------------------------

function getSpreadsheet_() {
  var id = PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');
  return id ? SpreadsheetApp.openById(id) : SpreadsheetApp.getActiveSpreadsheet();
}

/**
 * Makes sure every tab and required header exists. Never deletes, clears or
 * reorders anything: missing tabs are created, missing headers are appended at
 * the end of row 1. Rows are always written by header name, so staff may add
 * or move columns safely.
 */
function ensureSheets_(ss) {
  var tables = {};
  Object.keys(SHEET_HEADERS).forEach(function (name) {
    var sheet = ss.getSheetByName(name) || ss.insertSheet(name);
    var required = SHEET_HEADERS[name];
    var lastColumn = sheet.getLastColumn();
    var headers = lastColumn > 0 ? sheet.getRange(1, 1, 1, lastColumn).getValues()[0].map(String) : [];
    var missing = required.filter(function (h) { return headers.indexOf(h) === -1; });
    if (missing.length > 0) {
      sheet.getRange(1, headers.length + 1, 1, missing.length).setValues([missing]);
      headers = headers.concat(missing);
      sheet.setFrozenRows(1);
    }
    tables[name] = { sheet: sheet, headers: headers };
  });
  return tables;
}

function columnValues_(table, header) {
  var col = table.headers.indexOf(header) + 1;
  var lastRow = table.sheet.getLastRow();
  if (col === 0 || lastRow < 2) return [];
  return table.sheet.getRange(2, col, lastRow - 1, 1).getValues().map(function (r) { return r[0]; });
}

/** First data row where `header` equals `value` → { row, values: {header: value} }, or null. */
function findRow_(table, header, value) {
  var values = columnValues_(table, header);
  for (var i = 0; i < values.length; i++) {
    if (String(values[i]) === String(value)) {
      var row = i + 2;
      var cells = table.sheet.getRange(row, 1, 1, table.headers.length).getValues()[0];
      var record = {};
      table.headers.forEach(function (h, j) { record[h] = cells[j]; });
      return { row: row, values: record };
    }
  }
  return null;
}

function appendRows_(table, records) {
  var row = table.sheet.getLastRow() + 1;
  var matrix = records.map(function (record) {
    return table.headers.map(function (h) { return cell_(record[h]); });
  });
  table.sheet.getRange(row, 1, matrix.length, table.headers.length).setValues(matrix);
  return { table: table, row: row, count: matrix.length };
}

/**
 * Rewrites the whole row. Unchanged cells are written back through cell_() too:
 * getValues() returns text without its protecting apostrophe, and writing it back
 * raw would let Sheets re-parse "+8801…" or "2026-09-30 …" into numbers/dates.
 */
function updateRow_(table, row, fields) {
  var range = table.sheet.getRange(row, 1, 1, table.headers.length);
  var cells = range.getValues()[0];
  Object.keys(fields).forEach(function (h) {
    var col = table.headers.indexOf(h);
    if (col !== -1) cells[col] = fields[h];
  });
  range.setValues([cells.map(cell_)]);
}

/**
 * Cell value. Numbers, booleans and dates are written as-is. Strings are stored
 * as plain text: a leading apostrophe keeps "+8801…" phones and "1710" postcodes
 * as typed, and stops customer text that starts with = + - @ from being treated
 * as a formula (formula injection).
 */
function cell_(value) {
  if (value === null || value === undefined) return '';
  if (typeof value === 'number' || typeof value === 'boolean' || value instanceof Date) return value;
  var text = String(value);
  return text === '' ? '' : "'" + text;
}

function formatTimestamp_(value) {
  return value instanceof Date ? Utilities.formatDate(value, TIMEZONE, 'yyyy-MM-dd HH:mm:ss') : String(value);
}

function pad_(n, width) {
  var s = String(n);
  while (s.length < width) s = '0' + s;
  return s;
}

function json_(data) {
  return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON);
}

// ---- Controlled operations. No onEdit trigger: manual status edits NEVER restock. ----
var LOW_STOCK_THRESHOLD = 5;
var ORDER_STATUSES = ['Pending', 'Confirmed', 'Processing', 'Shipped', 'Delivered', 'Cancelled'];
var STATUS_NEXT = { Pending: 'Confirmed', Confirmed: 'Processing', Processing: 'Shipped', Shipped: 'Delivered' };
var OPERATION_ERRORS = {
  ORDER_NOT_FOUND: 'Order not found.',
  INVALID_STATUS_TRANSITION: 'This status change is not allowed. Use cancelOrder for cancellation.',
  ORDER_ALREADY_CANCELLED: 'This order is already cancelled.',
  ORDER_ALREADY_SHIPPED: 'Shipped or delivered orders require a separate returns workflow.',
  RESTOCK_FAILED: 'Restock failed. Inspect the order and audit records before recovery.',
  INVALID_INPUT: 'Provide a valid order ID and a note/reason of at most 300 characters.',
  STATUS_UPDATE_FAILED: 'Status update failed. Inspect the order history before retrying.',
  BUSY: 'Another operation is running. Please retry.'
};
function operationError_(code) { return { success: false, code: code, message: OPERATION_ERRORS[code] }; }
function operationResponse_(orderId, values) {
  return { success: true, orderId: orderId, status: String(values.order_status), restockStatus: String(values.restock_status || 'Not Required') };
}
function validOrderId_(id) { return typeof id === 'string' && /^SAD-\d{8}-\d{4,}$/.test(id); }
function records_(table) {
  if (table.sheet.getLastRow() < 2) return [];
  return table.sheet.getRange(2, 1, table.sheet.getLastRow() - 1, table.headers.length).getValues().map(function (cells) {
    var record = {};
    table.headers.forEach(function (h, i) { record[h] = cells[i]; });
    return record;
  });
}
// Register undo BEFORE writing, including an append that may write then throw.
function appendOperational_(table, records, undo) {
  var first = table.sheet.getLastRow() + 1;
  undo.push(function () {
    var count = Math.min(records.length, table.sheet.getLastRow() - first + 1);
    if (count > 0) table.sheet.deleteRows(first, count);
  });
  appendRows_(table, records);
}
function history_(t, orderId, from, to, note, now, undo) {
  appendOperational_(t.OrderStatusHistory, [{
    history_id: 'OSH-' + pad_(nextSequence_(t.OrderStatusHistory, 'history_id', 'OSH-'), 6),
    created_at: now, order_id: orderId, from_status: from, to_status: to, note: note || '', source: 'ADMIN'
  }], undo);
}
function rollbackOperational_(undo) {
  var ok = true;
  for (var i = undo.length - 1; i >= 0; i--) {
    try { undo[i](); } catch (err) { ok = false; console.error('Operational rollback failed: ' + err); }
  }
  try { SpreadsheetApp.flush(); } catch (err) { ok = false; }
  return ok;
}
function updateOrderStatus(orderId, newStatus, note) {
  if (!validOrderId_(orderId) || !isText_(note, 300, true)) return operationError_('INVALID_INPUT');
  var lock = LockService.getScriptLock();
  if (!lock.tryLock(LOCK_TIMEOUT_MS)) return operationError_('BUSY');
  try {
    var t = ensureSheets_(getSpreadsheet_());
    var order = findRow_(t.Orders, 'order_id', orderId);
    if (!order) return operationError_('ORDER_NOT_FOUND');
    var from = String(order.values.order_status);
    if (from === 'Cancelled') return operationError_('ORDER_ALREADY_CANCELLED');
    if (newStatus === 'Cancelled' || STATUS_NEXT[from] !== newStatus || ORDER_STATUSES.indexOf(newStatus) < 0 || /^(Pending|Failed)$/.test(String(order.values.restock_status))) return operationError_('INVALID_STATUS_TRANSITION');
    var undo = [updateRowUndo_(t.Orders, order.row)];
    var now = Utilities.formatDate(new Date(), TIMEZONE, 'yyyy-MM-dd HH:mm:ss');
    try {
      updateRow_(t.Orders, order.row, { order_status: newStatus, status_updated_at: now, status_note: note || '' });
      history_(t, orderId, from, newStatus, note, now, undo);
      SpreadsheetApp.flush();
      return operationResponse_(orderId, { order_status: newStatus, restock_status: order.values.restock_status });
    } catch (err) {
      rollbackOperational_(undo);
      return operationError_('STATUS_UPDATE_FAILED');
    }
  } finally { lock.releaseLock(); }
}
function cancelOrder(orderId, reason) {
  if (!validOrderId_(orderId) || !isText_(reason, 300) || reason.trim().length < 3) return operationError_('INVALID_INPUT');
  var lock = LockService.getScriptLock();
  if (!lock.tryLock(LOCK_TIMEOUT_MS)) return operationError_('BUSY');
  try {
    var t = ensureSheets_(getSpreadsheet_());
    var order = findRow_(t.Orders, 'order_id', orderId);
    if (!order) return operationError_('ORDER_NOT_FOUND');
    var from = String(order.values.order_status);
    // Pending/Failed is a durable safety fence, including interrupted executions.
    if (/^(Pending|Failed)$/.test(String(order.values.restock_status))) return operationError_('RESTOCK_FAILED');
    if (from === 'Cancelled') return operationResponse_(orderId, order.values);
    if (from === 'Shipped' || from === 'Delivered') return operationError_('ORDER_ALREADY_SHIPPED');
    if (['Pending', 'Confirmed', 'Processing'].indexOf(from) < 0) return operationError_('INVALID_STATUS_TRANSITION');
    var undo = [];
    try {
      var items = records_(t.OrderItems).filter(function (r) { return String(r.order_id) === orderId; });
      if (!items.length) throw new Error('Order items missing');
      var quantities = Object.create(null);
      items.forEach(function (r) {
        var q = Number(r.quantity);
        if (!Number.isSafeInteger(q) || q < 1) throw new Error('Invalid order quantity');
        quantities[r.product_id] = (quantities[r.product_id] || 0) + q;
      });
      var audit = records_(t.InventoryTransactions).filter(function (r) { return String(r.order_id) === orderId; });
      // Any prior RESTOCK with a non-cancelled order needs reconciliation, never another credit.
      if (audit.some(function (r) { return r.type === 'RESTOCK'; })) throw new Error('Prior restock exists');
      var inventory = loadInventory_(t.Products);
      var restores = [];
      Object.keys(quantities).forEach(function (id) {
        var sales = audit.filter(function (r) { return r.product_id === id && r.type === 'SALE'; });
        var sold = sales.reduce(function (sum, r) { return sum - Number(r.quantity); }, 0);
        var product = inventory[id];
        if (!product && sales.length) throw new Error('Sold product missing');
        if (!product || !product.trackStock) return;
        if (PropertiesService.getScriptProperties().getProperty('INVENTORY_FENCE_' + id)) throw new Error('Inventory requires reconciliation');
        // Products switched from untracked to tracked must not receive stock never deducted.
        if (!sales.length) return;
        if (sold !== quantities[id] || product.stock === null || !Number.isSafeInteger(product.stock + sold)) throw new Error('Inventory audit mismatch');
        restores.push({ product: product, quantity: sold });
      });
      var now = Utilities.formatDate(new Date(), TIMEZONE, 'yyyy-MM-dd HH:mm:ss');
      // Persist the fence before changing stock. Keep it if rollback is incomplete.
      updateRow_(t.Orders, order.row, { restock_status: 'Pending' });
      SpreadsheetApp.flush();
      var transactions = [];
      restores.forEach(function (x) {
        undo.push(updateRowUndo_(t.Products, x.product.row));
        updateRow_(t.Products, x.product.row, { stock: x.product.stock + x.quantity, updated_at: now });
        transactions.push({ created_at: now, product_id: x.product.productId, order_id: orderId, type: 'RESTOCK', quantity: x.quantity, stock_before: x.product.stock, stock_after: x.product.stock + x.quantity, note: 'Order cancelled: ' + reason.trim() });
      });
      if (transactions.length) {
        var seq = nextSequence_(t.InventoryTransactions, 'transaction_id', 'INV-');
        transactions.forEach(function (tx, i) { tx.transaction_id = 'INV-' + pad_(seq + i, 6); });
        appendOperational_(t.InventoryTransactions, transactions, undo);
      }
      history_(t, orderId, from, 'Cancelled', reason.trim(), now, undo);
      var fields = { order_status: 'Cancelled', status_updated_at: now, status_note: reason.trim(), cancelled_at: now, cancel_reason: reason.trim(), restock_status: restores.length ? 'Restored' : 'Not Required' };
      // On failure restore the original status but retain the Pending fence until rollback completes.
      undo.push(function () { updateRow_(t.Orders, order.row, { order_status: from, status_updated_at: order.values.status_updated_at || '', status_note: order.values.status_note || '', cancelled_at: order.values.cancelled_at || '', cancel_reason: order.values.cancel_reason || '', restock_status: 'Pending' }); });
      updateRow_(t.Orders, order.row, fields);
      SpreadsheetApp.flush();
      return operationResponse_(orderId, fields);
    } catch (err) {
      console.error('Cancellation failed: ' + err);
      rollbackOperational_(undo);
      try { updateRow_(t.Orders, order.row, { order_status: from, restock_status: 'Failed' }); SpreadsheetApp.flush(); } catch (failure) { console.error('Failure marker could not be saved'); }
      // Failed requires an explicit audited recovery, even when rollback succeeded.
      return operationError_('RESTOCK_FAILED');
    }
  } finally { lock.releaseLock(); }
}
function getLowStockProducts() {
  var ss = getSpreadsheet_();
  var sheet = ss.getSheetByName('Products');
  if (!sheet || !sheet.getLastColumn()) return { success: true, products: [] };
  var table = { sheet: sheet, headers: sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0].map(String) };
  var inventory = loadInventory_(table);
  var names = Object.create(null);
  records_(table).forEach(function (r) { if (!names[r.product_id]) names[r.product_id] = String(r.product_name); });
  return { success: true, products: Object.keys(inventory).filter(function (id) {
    var p = inventory[id]; return p.trackStock && p.stock !== null && p.stock <= LOW_STOCK_THRESHOLD;
  }).map(function (id) {
    var p = inventory[id];
    return { product_id: id, product_name: names[id], stock: p.stock, status: p.stock === 0 ? 'Out of Stock' : 'Low Stock', updated_at: p.updatedAt };
  }) };
}
function sendLowStockReport() {
  var recipient = PropertiesService.getScriptProperties().getProperty('LOW_STOCK_REPORT_EMAIL');
  if (!recipient || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recipient)) throw new Error('Configure LOW_STOCK_REPORT_EMAIL explicitly first.');
  var products = getLowStockProducts().products;
  MailApp.sendEmail(recipient, 'Sadira low-stock report', products.length ? products.map(function (p) { return p.product_id + ' | ' + p.product_name + ' | ' + p.stock + ' | ' + p.status; }).join('\n') : 'No low-stock products.');
}
function testUpdateOrderStatus() {
  return updateOrderStatus('REPLACE_WITH_ORDER_ID', 'Confirmed', 'Customer confirmed by phone');
}
function testCancelOrder() {
  return cancelOrder('REPLACE_WITH_ORDER_ID', 'Customer requested cancellation');
}

// ---- Phase 13: authenticated server-only admin adapter ------------------------
// doPost checks APPS_SCRIPT_SECRET before dispatch. Next.js verifies the staff session.
var ADMIN_ORDER_FIELDS = ['order_id', 'created_at', 'customer_name', 'phone', 'total', 'payment_method', 'payment_status', 'order_status'];
var ADMIN_CUSTOMER_FIELDS = ['customer_id', 'name', 'phone', 'email', 'total_orders', 'first_order_at', 'last_order_at'];
function adminPick_(record, fields) {
  var out = {};
  fields.forEach(function (key) {
    var value = record[key];
    out[key] = value instanceof Date ? formatTimestamp_(value) : value === undefined ? '' : value;
  });
  return out;
}
function adminPage_(rows, b) {
  var pageSize = 25;
  var requested = Number(b.page || 1);
  var page = Number.isSafeInteger(requested) && requested > 0 ? requested : 1;
  page = Math.min(page, Math.max(1, Math.ceil(rows.length / pageSize)));
  return { rows: rows.slice((page - 1) * pageSize, page * pageSize), total: rows.length, page: page, pageSize: pageSize };
}
function adminSearch_(rows, query, fields) {
  var q = typeof query === 'string' ? query.trim().slice(0, 100).toLowerCase() : '';
  return q ? rows.filter(function (r) { return fields.some(function (h) { return String(r[h] || '').toLowerCase().indexOf(q) !== -1; }); }) : rows;
}
function adminNewest_(rows) {
  return rows.sort(function (a, b) { return String(b.created_at).localeCompare(String(a.created_at)) || String(b.order_id || b.transaction_id).localeCompare(String(a.order_id || a.transaction_id)); });
}
function adminInventory_(t) {
  var inventory = loadInventory_(t.Products);
  return records_(t.Products).filter(function (r, i, rows) { return rows.findIndex(function (x) { return x.product_id === r.product_id; }) === i; }).map(function (r) {
    var p = inventory[String(r.product_id)];
    if (!p) return null;
    return { product_id: p.productId, product_name: String(r.product_name), track_stock: p.trackStock, stock: p.stock === null ? '' : p.stock, status: p.status, updated_at: p.updatedAt,
      stock_state: !p.trackStock ? 'Untracked' : p.stock === null ? 'Invalid Stock' : p.stock === 0 ? 'Out of Stock' : p.stock <= LOW_STOCK_THRESHOLD ? 'Low Stock' : 'In Stock',
      recovery_required: !!PropertiesService.getScriptProperties().getProperty('INVENTORY_FENCE_' + p.productId) };
  }).filter(function (r) { return r !== null; });
}
function adminAction_(b) {
  if (b.action === 'adminUpdateOrderStatus') return updateOrderStatus(b.orderId, b.newStatus, b.note);
  if (b.action === 'adminCancelOrder') return cancelOrder(b.orderId, b.reason);
  if (['adminAdjustStock', 'adminSetProductStatus', 'adminSetTracking'].indexOf(b.action) !== -1) return adminMutateInventory_(b);
  if (['adminGetDashboard', 'adminListOrders', 'adminGetOrder', 'adminListInventory', 'adminListTransactions', 'adminListCustomers'].indexOf(b.action) === -1) return operationError_('INVALID_INPUT');
  var lock = LockService.getScriptLock();
  if (!lock.tryLock(LOCK_TIMEOUT_MS)) return operationError_('BUSY');
  try {
    var t = ensureSheets_(getSpreadsheet_());
    var data;
    if (b.action === 'adminListCustomers') {
      var customers = records_(t.Customers).map(function (r) { return adminPick_(r, ADMIN_CUSTOMER_FIELDS); });
      customers.sort(function (a, c) { return String(c.last_order_at).localeCompare(String(a.last_order_at)); });
      data = adminPage_(adminSearch_(customers, b.q, ['customer_id', 'name', 'phone']), b);
    } else if (b.action === 'adminListInventory') {
      var products = adminInventory_(t);
      // Low-stock selection derives from the Phase 12 report, preserving its central threshold.
      var low = getLowStockProducts().products;
      if (b.filter === 'low') products = products.filter(function (p) { return low.some(function (x) { return x.product_id === p.product_id && x.status === 'Low Stock'; }); });
      if (b.filter === 'out') products = products.filter(function (p) { return low.some(function (x) { return x.product_id === p.product_id && x.status === 'Out of Stock'; }); });
      if (b.filter === 'tracked') products = products.filter(function (p) { return p.track_stock; });
      data = adminPage_(adminSearch_(products, b.q, ['product_id', 'product_name']), b);
    } else if (b.action === 'adminListTransactions') {
      var txs = records_(t.InventoryTransactions).map(function (r) { return adminPick_(r, SHEET_HEADERS.InventoryTransactions); });
      data = adminPage_(adminNewest_(txs), b);
    } else if (b.action === 'adminGetOrder') {
      if (!validOrderId_(b.orderId)) return operationError_('INVALID_INPUT');
      var found = findRow_(t.Orders, 'order_id', b.orderId);
      if (!found) return operationError_('ORDER_NOT_FOUND');
      var items = records_(t.OrderItems).filter(function (r) { return String(r.order_id) === b.orderId; });
      var tx = records_(t.InventoryTransactions).filter(function (r) { return String(r.order_id) === b.orderId; });
      var inv = loadInventory_(t.Products);
      data = { order: adminPick_(found.values, SHEET_HEADERS.Orders.filter(function (h) { return h !== 'request_id'; })), items: items.map(function (r) { return adminPick_(r, SHEET_HEADERS.OrderItems); }), history: records_(t.OrderStatusHistory).filter(function (r) { return String(r.order_id) === b.orderId; }).map(function (r) { return adminPick_(r, SHEET_HEADERS.OrderStatusHistory); }), transactions: tx.map(function (r) { return adminPick_(r, SHEET_HEADERS.InventoryTransactions); }), hasTrackedItems: items.some(function (r) { return inv[r.product_id] && inv[r.product_id].trackStock && tx.some(function (x) { return x.product_id === r.product_id && x.type === 'SALE'; }); }) };
    } else {
      var counts = Object.create(null);
      records_(t.OrderItems).forEach(function (r) { counts[r.order_id] = (counts[r.order_id] || 0) + Number(r.quantity); });
      var orders = adminNewest_(records_(t.Orders).map(function (r) {
        var order = adminPick_(r, ADMIN_ORDER_FIELDS); order.items = counts[r.order_id] || 0; return order;
      }));
      if (b.action === 'adminListOrders') {
        if (ORDER_STATUSES.indexOf(b.status) !== -1) orders = orders.filter(function (r) { return r.order_status === b.status; });
        orders = adminSearch_(orders, b.q, ['order_id', 'customer_name', 'phone']);
        if (b.sort === 'oldest') orders.reverse();
        if (b.sort === 'total-high') orders.sort(function (a, c) { return Number(c.total) - Number(a.total); });
        if (b.sort === 'total-low') orders.sort(function (a, c) { return Number(a.total) - Number(c.total); });
        data = adminPage_(orders, b);
      } else {
        var today = Utilities.formatDate(new Date(), TIMEZONE, 'yyyy-MM-dd').slice(0, 10);
        var todaysOrders = orders.filter(function (r) { return String(r.created_at).slice(0, 10) === today; });
        var metrics = { 'Today Orders': todaysOrders.length, 'Today Revenue': todaysOrders.filter(function (r) { return r.order_status !== 'Cancelled'; }).reduce(function (sum, r) { return sum + Number(r.total || 0); }, 0) };
        ['Pending', 'Confirmed', 'Processing', 'Delivered', 'Cancelled'].forEach(function (status) { metrics[status + ' Orders'] = orders.filter(function (r) { return r.order_status === status; }).length; });
        var lowProducts = getLowStockProducts().products;
        metrics['Low Stock Products'] = lowProducts.filter(function (p) { return p.status === 'Low Stock'; }).length;
        metrics['Out of Stock Products'] = lowProducts.filter(function (p) { return p.status === 'Out of Stock'; }).length;
        data = { today: today, metrics: metrics, recentOrders: orders.slice(0, 10) };
      }
    }
    return { success: true, data: data };
  } catch (err) { console.error('Admin read failed: ' + err); return { success: false, code: 'ADMIN_LOAD_FAILED', message: 'Unable to load operational data.' }; }
  finally { lock.releaseLock(); }
}
function adminMutateInventory_(b) {
  if (typeof b.productId !== 'string' || !/^[A-Za-z0-9-]{1,64}$/.test(b.productId)) return { success: false, code: 'INVALID_INPUT' };
  if (b.action !== 'adminSetProductStatus' && (!isText_(b.reason, 300) || b.reason.trim().length < 3)) return { success: false, code: 'INVALID_INPUT' };
  if (b.action === 'adminSetProductStatus' && ['active', 'inactive'].indexOf(b.status) === -1) return { success: false, code: 'INVALID_INPUT' };
  if (b.action === 'adminSetTracking' && typeof b.trackStock !== 'boolean') return { success: false, code: 'INVALID_INPUT' };
  if ((b.action === 'adminAdjustStock' || (b.action === 'adminSetTracking' && b.trackStock)) && (!Number.isSafeInteger(b.stock) || b.stock < 0)) return { success: false, code: 'INVALID_INPUT' };
  var lock = LockService.getScriptLock();
  if (!lock.tryLock(LOCK_TIMEOUT_MS)) return operationError_('BUSY');
  try {
    var t = ensureSheets_(getSpreadsheet_());
    var props = PropertiesService.getScriptProperties();
    var fenceKey = 'INVENTORY_FENCE_' + b.productId;
    if (props.getProperty(fenceKey) || props.getProperty('CATALOG_FENCE_' + b.productId)) return { success: false, code: 'ADJUSTMENT_FAILED' };
    var product = loadInventory_(t.Products)[b.productId];
    if (!product) return { success: false, code: 'PRODUCT_NOT_FOUND' };
    if (b.expectedTracking !== product.trackStock || b.expectedStock !== product.stock || b.expectedStatus !== product.status) return { success: false, code: 'INVENTORY_CHANGED' };
    if (b.action === 'adminAdjustStock' && !product.trackStock) return { success: false, code: 'UNTRACKED_PRODUCT' };
    var fields = {};
    var before = product.trackStock ? product.stock : 0;
    var after = before;
    if (b.action === 'adminSetProductStatus') fields.status = b.status;
    if (b.action === 'adminAdjustStock') { if (before === null) return { success: false, code: 'INVALID_INPUT' }; fields.stock = b.stock; after = b.stock; }
    if (b.action === 'adminSetTracking') {
      fields.track_stock = b.trackStock;
      if (b.trackStock) { if (before === null) return { success: false, code: 'INVALID_INPUT' }; fields.stock = b.stock; after = b.stock; }
      // Disabling tracking retains the last stock; no deduction is implied.
    }
    var now = Utilities.formatDate(new Date(), TIMEZONE, 'yyyy-MM-dd HH:mm:ss');
    fields.updated_at = now;
    var undo = [updateRowUndo_(t.Products, product.row)];
    try {
      // Durable journal fences interrupted writes and failed rollbacks; storefront fails closed.
      props.setProperty(fenceKey, JSON.stringify({ action: b.action, before: before, after: after, created_at: now }));
      updateRow_(t.Products, product.row, fields);
      if (b.action === 'adminSetProductStatus') {
        var catalogRow = findRow_(t.Catalog, 'product_id', b.productId);
        if (catalogRow) {
          var content = JSON.parse(catalogRow.values.product_json);
          content.status = b.status === 'active' ? 'active' : 'archived';
          undo.push(updateRowUndo_(t.Catalog, catalogRow.row));
          updateRow_(t.Catalog, catalogRow.row, { product_json: JSON.stringify(content), revision: Utilities.getUuid(), updated_at: now });
        }
      }
      if (after !== before) {
        appendOperational_(t.InventoryTransactions, [{ transaction_id: 'INV-' + pad_(nextSequence_(t.InventoryTransactions, 'transaction_id', 'INV-'), 6), created_at: now, product_id: b.productId, order_id: '', type: after > before ? 'ADJUSTMENT_IN' : 'ADJUSTMENT_OUT', quantity: after - before, stock_before: before, stock_after: after, note: 'Manual admin adjustment: ' + b.reason.trim() }], undo);
      }
      SpreadsheetApp.flush();
      props.deleteProperty(fenceKey);
      return { success: true, productId: b.productId };
    } catch (err) {
      var ok = rollbackOperational_(undo);
      if (ok) { try { props.deleteProperty(fenceKey); } catch (failure) { console.error('Inventory fence remains'); } }
      console.error('Admin inventory mutation failed: ' + err);
      return { success: false, code: 'ADJUSTMENT_FAILED' };
    }
  } finally { lock.releaseLock(); }
}
