/**
 * GENERATED by `npm run catalog:prepare` (scripts/generate-inventory-seed.mjs) — do not edit by hand.
 *
 * Initial inventory for setupInventory() in Code.gs. Used ONLY to create a
 * Products row for a product that doesn't have one yet; existing rows (live
 * stock) are never changed. stock: null = not tracked (NOT zero).
 *
 * Paste this file into the same Apps Script project as Code.gs.
 */

var SADIRA_PRODUCT_SEED = [
  { productId: "SAD-ABAYA-001", productName: "Abaya Elara", stock: null },
  { productId: "SAD-ABAYA-002", productName: "Abaya Haya", stock: null },
  { productId: "SAD-ABAYA-003", productName: "Abaya Zahra (زهراء)", stock: null },
  { productId: "SAD-BAG-001", productName: "Shoulder Bag", stock: null },
  { productId: "SAD-BAG-002", productName: "YSL Embroidery Bag", stock: null },
  { productId: "SAD-BRACELET-001", productName: "MK Bracelet Watch", stock: null },
  { productId: "SAD-NIQAB-001", productName: "Premium Saudi Chiffon Niqab", stock: null },
  { productId: "SAD-SCARF-001", productName: "Brand Scarf Collection", stock: 4000 },
  { productId: "SAD-SUNGLASS-001", productName: "Prada Milano Sunglasses", stock: 12 },
  { productId: "SAD-ABAYA-004", productName: "Abaya Hiraa", stock: null },
  { productId: "SAD-ABAYA-005", productName: "Shirt Abaya", stock: null },
  { productId: "SAD-BRACELET-002", productName: "MK Signature Watch", stock: null },
  { productId: "SAD-COMBO-001", productName: "Abaya & Hijab Combo", stock: null },
  { productId: "SAD-PERFUME-001", productName: "Gucci Mini Perfume (Master Copy)", stock: null },
  { productId: "SAD-BAG-003", productName: "PU Leather Bag", stock: null },
  { productId: "SAD-BAG-004", productName: "Floral Charm Shoulder Bag", stock: null },
  { productId: "SAD-ABAYA-006", productName: "Cherry Fabrics Plain Abaya", stock: null },
  { productId: "SAD-ABAYA-007", productName: "Olive Abaya", stock: 15 },
  { productId: "SAD-ABAYA-008", productName: "Popcorn Fabrics Abaya", stock: null },
  { productId: "SAD-SCARF-002", productName: "Leopard Print Hijab", stock: null },
  { productId: "SAD-COMBO-002", productName: "Abaya & Accessories Combo", stock: null },
  { productId: "SAD-CLIP-001", productName: "Sunflower Hair Clip", stock: null }
];
