import Link from "next/link";
import { listInventory, listTransactions, safeLoad } from "@/services/adminService";
import { Badge, DataTable, Heading, LoadError, Pagination, transactionColumns } from "@/components/admin/Data";
import { ProductActions } from "@/components/admin/ProductActions";
export default async function Inventory({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams; const query = Object.fromEntries(Object.entries(raw).filter((p): p is [string, string] => typeof p[1] === "string"));
  const results = await Promise.allSettled([safeLoad(() => listInventory({ ...query, filter: query.filter || "low" })), safeLoad(() => listTransactions({ page: query.txpage || 1 }))]);
  for (const result of results) if (result.status === "rejected") throw result.reason;
  const products = results[0].status === "fulfilled" ? results[0].value : null; const history = results[1].status === "fulfilled" ? results[1].value : null;
  return <><Heading title="Inventory" description="Monitor stock levels and inspect every inventory movement." /><section className="admin-card"><form className="admin-filters" action="/admin/inventory"><label>Search inventory<input name="q" defaultValue={query.q} placeholder="Product name or ID" maxLength={100} /></label><label>Stock view<select name="filter" defaultValue={query.filter || "low"}><option value="low">Low Stock</option><option value="out">Out of Stock</option><option value="tracked">All Tracked Products</option></select></label><button className="admin-button primary">Apply</button></form>{products ? <><DataTable rows={products.rows} empty={query.filter === "out" ? "No out-of-stock products." : query.filter === "tracked" ? "No tracked products found." : "No low-stock products."} columns={[{ key: "product_name", label: "Product" }, { key: "product_id", label: "Product ID" }, { key: "stock", label: "Current stock" }, { key: "stock_state", label: "Stock status", render: r => <Badge value={r.stock_state} /> }, { key: "status", label: "Availability", render: r => <Badge value={r.status} /> }, { key: "updated_at", label: "Last updated" }, { key: "actions", label: "Actions", render: r => <><ProductActions product={r} stockOnly /><Link className="admin-text-link" href={`/admin/products?q=${encodeURIComponent(String(r.product_id))}`}>View Product →</Link></> }]} /><Pagination data={products} base="/admin/inventory" query={{ ...query, filter: query.filter || "low" }} /></> : <LoadError />}</section>
    <section className="admin-card"><h2>Inventory history</h2>{history ? <><DataTable rows={history.rows} columns={transactionColumns} empty="No inventory transactions yet." /><Pagination data={history} base="/admin/inventory" query={query} pageKey="txpage" /></> : <LoadError />}</section>
  </>;
}
